package iapx.qPkt;

import iapx.Kind;
import iapx.Opcode;
import iapx.value.MemAddr;

//Visible Record Qfrm5:Qpkt;
//begin infix(MemAddr) addr;
//      range(0:MaxWord) aux;
//      ref(Qpkt) dst;
//end;
public class Qfrm5 extends Qpkt {
	public MemAddr addr;
	int aux;
	public Qpkt dst;
//	------------------------------------------------------------------------
//	-- Format 5.  Generated by Qf5(fnc,subc,addr)
//	------------------------------------------------------------------------
//	Visible Record Qfrm5:Qpkt;
//	begin infix(MemAddr) addr;
//	      range(0:MaxWord) aux;
//	      ref(Qpkt) dst;
//	end;
//	------------------------------------------------------------------------
//	-- Mnemonic = FNC //   SUBC   REG    AUX   other   subcodes/comments
//	------------------------------------------------------------------------
	public final static int
	   qCALL    = 60, //   subc         pxlng  addr
	                                                   qEXIT=1, qXNX=2,
	                                                   qOS2=3,  qC=4,
	                                                   qKNL=5,
	   qJMP     = 61; //   subc                addr dst // Same subc as CONDEC 
	                                                    // plus subc=0

	public Qfrm5(Opcode fnc, int pkind, int reg, int aux, MemAddr addr) {
		this.kind = Kind.K_Qfrm5;
		this.fnc = fnc; this.subc = pkind; this.reg = reg; this.aux = aux;
		this.addr = addr;
	}

}
