package iapx.qPkt;

import iapx.Kind;
import iapx.Opcode;
import iapx.value.Value;

//Visible Record Qfrm2:Qpkt;
//begin infix(wWORD) aux end;
public class Qfrm2 extends Qpkt {
	Value aux;
//	------------------------------------------------------------------------
//	-- Format 2.  Generated by Qf2(fnc,subc,reg,aux)
//	------------------------------------------------------------------------
	public Qfrm2(Opcode fnc, int subc, int reg, int type, Value aux) {
		this.kind = Kind.K_Qfrm2;
		this.fnc = fnc; this.subc = subc; this.reg = reg; this.aux = aux;
	}

//	------------------------------------------------------------------------
//	-- Mnemonic = FNC //   SUBC   REG    AUX   other   subcodes/comments
//	------------------------------------------------------------------------
	public final static int
	   qRSTRB   = 17, //   subc   dir    rep
	   qRSTRW   = 18, //   subc   dir    rep
	                                                   qRMOV=1,   // subc
	                                                   qRCMP=2,   // subc
	                                                   qZERO=3,   // subc
	                                                   qRCMPS=4,  // subc
	                                                   qRSCAS=5,  // subc
	                                                   qRSTOS=6,  // subc
	                                                   qCLD=0,    // dir
	                                                   qSTD=1,    // dir
	                                                   qREP=0,    // rep
	                                                   qREPEQ=1,  // rep
	                                                   qREPNE=2,  // rep
	   qMONADR  = 19, //   subc   reg
	                                                   qNOT=1, qNEGM=8,
	                                                   qNEG=2, qNEGF=9,
	                                                   qINC=3, qINCF=10,
	                                                   qDEC=4, qDECF=11,
	                                                   qSHL1=5,qSHL1F=12,
	                                                   qSHR1=6,qSHR1F=13,
	                                                   qSAR1=7,qSAR1F=14,
	   qTRIADR  = 20, //   subc   reg
	                                                   qWMUL=1,  qWMULF=5,
	                                                   qWDIV=2,  qWDIVF=6,
	                                                   qWMOD=3,  qWMODF=7,
	                                                   qIMUL=9,  qIMULF=13,
	                                                   qIDIV=10, qIDIVF=14,
	                                                   qIMOD=11, qIMODF=15,
	   qCONDEC  = 21, //   subc   reg
	                                                   q_WLT=1,  q_WLE=2,
	                                                   q_WEQ=3,  q_WGE=4,
	                                                   q_WGT=5,  q_WNE=6,
	                                                   q_ILT=9,  q_ILE=10,
	                                                   q_IEQ=11, q_IGE=12,
	                                                   q_IGT=13, q_INE=14,
	   qMOV     = 22, //          reg    reg2
	                                               qSEXT=1, qZEXT=2,
	   qXCHG    = 23, //          reg    reg2
	   qDYADR   = 24, //   subc   reg    reg2
	                                                   qAND=1,  qOR=2,
	                                                   qXOR=3,
	                                                   qANDM=4, qORM=5,
	                                                   qXORM=6,
	                                                   qINCO=7, qDECO=8,
	                                                   qCMP=9,  qADD=10,
	                                                   qSUB=11,
	                                                   qADDM=12,qSUBM=13,
	                                                   qADC=14, qSBB=15,
	                                                   qADDF=16,qSUBF=17,
	                                                   qADCF=18,qSBBF=19,
	   qSHIFT   = 25, //   subc   reg
	                                                   qSHL=1,qSHR=2,qSAR=3,
	   qPOPK    = 26, //                 const
	   qRET     = 27, //                 const
	   qINT     = 28, //                 const
	   qADJST   = 29, //                 const
	   qENTER   = 30, //                 const
	   qLEAVE   = 31, //                 const
	   qLINE    = 32, //   subc          const
	                                                   qDCL=1,qSTM=2,
	   qDYADC   = 33; //   subc   reg    const     // Same subcodes as DYADR

//	Const Range(0:14) NotQcond(16) = (
	int[] NotQcond = {
	// original:      <       <=      =       >=      >       <>         ---
	// test flipped:  >=      >       <>      <       <=      =          ---
	//----- 0       q_WLT   q_WLE   q_WEQ   q_WGE   q_WGT   q_WNE   7    ---
	        0,      q_WGE,  q_WGT,  q_WNE,  q_WLT,  q_WLE,  q_WEQ,  0,
	//----- 8       q_ILT   q_ILE   q_IEQ   q_IGE   q_IGT   q_INE   15   ---
	        0,      q_IGE,  q_IGT,  q_INE,  q_ILT,  q_ILE,  q_IEQ,  0 };

//	Const Range(0:14) RevQcond(16) = (
	int[] RevQcond = {
	// original:      <       <=      =       >=      >       <>         ---
	// data flipped:  >       >=      =       <=      <       <>         ---
	//----- 0       q_WLT   q_WLE   q_WEQ   q_WGE   q_WGT   q_WNE   7    ---
	        0,      q_WGT,  q_WGE,  q_WEQ,  q_WLE,  q_WLT,  q_WNE,  0,
	//----- 8       q_ILT   q_ILE   q_IEQ   q_IGE   q_IGT   q_INE   15   ---
	        0,      q_IGT,  q_IGE,  q_IEQ,  q_ILE,  q_ILT,  q_INE,  0 };

	
	@Override
	public String toString() {
		return 	"Qfrm2: fnc="+ fnc +",subc=" + subc + ", reg=" + reg + ", aux=" + aux;
	}

}
