{
  parserClass="com.simula.lang.parser.SimulaParser_FROM_Demo"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simula"
  psiImplClassSuffix="Impl"
  psiPackage="com.simula.lang.psi"
  psiImplPackage="com.simula.lang.psi.impl"

  elementTypeHolderClass="com.simula.lang.psi.SimulaTypes"
  elementTypeClass="com.simula.lang.psi.SimulaElementType"
  tokenTypeClass="com.simula.lang.psi.SimulaTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY