package iAPX.qPkt;

import iAPX.ValueItem;
import iAPX.dataAddress.MemAddr;
import iAPX.enums.Kind;
import iAPX.enums.Opcode;

public class Qfrm3 extends Qpkt {
	MemAddr opr;
	ValueItem val;
//	------------------------------------------------------------------------
//	-- Format 3.  Generated by Qf3(fnc,subc,reg,opr)
//	-- Format 3b. Generated by Qf3b(fnc,subc,reg,val)
//	------------------------------------------------------------------------
//	Visible Record Qfrm3:Qpkt;
//	begin variant infix(MemAddr) opr;
//	      variant infix(ValueItem) val;
//	end;
//	------------------------------------------------------------------------
//	-- Mnemonic = FNC //   SUBC   REG    AUX   other   subcodes/comments
//	------------------------------------------------------------------------
	public final static int
	   qJMPM    = 37, //                        opr
//	%-E qJMPFM  = 38, //                        opr
	qBOUND  = 39, //                        opr
	   qPUSHA   = 40, //          reg           opr
	   qLOADA   = 41, //          reg           opr
	   qSTORE   = 42, //          reg           opr
	   qXCHGM   = 43, //          reg           opr
	   qFLD     = 44, //   fSD    fmf           opr
//	%-E qFLDC   = 45, //   sreg   fmf       lrv/rev/val
	qFLDC   = 45, //   fSD    fmf       lrv/rev/val
	   qFST     = 46, //   fSD    fmf           opr
	   qFSTP    = 47, //   fSD    fmf           opr
	   qDYADM   = 48, //   subc   reg           opr   // Same subc as DYADR
	   qDYADMR  = 49, //   subc   reg           opr   // Same subc as DYADR
	   qMONADM  = 50, //   subc  width          opr   // Same subc as MONADR
	   qTRIADM  = 51; //   subc  width          opr   // Same subc as TRIADR

	public Qfrm3(Opcode fnc, int subc, int reg, int type, MemAddr opr) {
		this.kind = Kind.K_Qfrm3;
		this.fnc = fnc; this.subc = subc; this.reg = reg; this.opr = opr;
	}

	public Qfrm3(Opcode fnc, int subc, int reg, int type, ValueItem val) {
		this.kind = Kind.K_Qfrm3;
		this.fnc = fnc; this.subc = subc; this.reg = reg; this.val = val;
	}

}
