package iAPX.qPkt;

import iAPX.dataAddress.MemAddr;

public class Qfrm4b extends Qfrm4 {
	MemAddr addr;
//	------------------------------------------------------------------------
//	-- Format 4.  Generated by Qf4(fnc,subc,reg,aux,opr)
//	-- Format 4b. Generated by Qf4b(fnc,subc,reg,aux,opr,addr)
//	-- Format 4c. Generated by Qf4c(fnc,subc,reg,aux,opr,nrep)
//	------------------------------------------------------------------------
//	Visible Record Qfrm4:Qfrm3;
//	begin infix(wWORD) aux end;
//
//	Visible Record Qfrm4b:Qfrm4;
//	begin infix(MemAddr) addr end;
//
//	Visible Record Qfrm4c:Qfrm4;
//	begin range(0:MaxByte) nrep end;
//	------------------------------------------------------------------------
//	-- Mnemonic = FNC //   SUBC   REG    AUX   other   subcodes/comments
//	------------------------------------------------------------------------
	public final static int

	   qLOAD    = 52, //   subc   reg    ofst   opr nrep // Same subc as MOV
//	%-E qLDS    = 53, //          reg    ofst   opr nrep
//	%-E qLES    = 54, //          reg    ofst   opr nrep

	   qFDYADM  = 55, //   subc   fmf    fSD    opr   // Same subc as FDYAD
	   qPUSHM   = 56, //                const   opr
	   qPOPM    = 57, //          reg   const   opr
	   qMOVMC   = 58, //         width  const   opr
	                  //         width   fld    opr addr
	   qDYADMC  = 59; //   subc  width  const   opr   // Same subc as DYADR
	                  //   subc  width   fld    opr addr

}
