package iAPX.qPkt;

import iAPX.enums.Kind;
import iAPX.enums.Opcode;

public class Qfrm1 extends Qpkt {
	int aux;
	
//	------------------------------------------------------------------------
//	-- Format 1.  Generated by Qf1(fnc,subc)   or   Qf1b(fnc,subc,reg)
//	------------------------------------------------------------------------
//	public Qfrm1(Opcode fnc, int subc, int reg, int type, int aux) {
//		this.kind = Kind.K_Qfrm1;
//		this.fnc = fnc; this.subc = subc; this.reg = reg; this.aux = aux;
//	}
	public Qfrm1(Opcode fnc, int reg, int aux) {
		this.kind = Kind.K_Qfrm1;
		this.fnc = fnc; this.reg = reg; this.aux = aux;
	}
//	Visible Record Qfrm1:Qpkt; begin end;
//	------------------------------------------------------------------------
//	-- Mnemonic = FNC //   SUBC   REG    AUX   other   subcodes/comments
//	------------------------------------------------------------------------
	public final static int
	   qWAIT    =  1, //
	   qEVAL    =  2, //
	   qTSTOFL  =  3, //  val
	   qLAHF    =  4, //
	   qSAHF    =  5, //
	   qCWD     =  6, // width
	   qFDUP    =  7, //  fSD
	   qIRET    =  8, //
	   qDOS2    =  9, //
	   qFLDCK   = 10, // subc
	                                                   qFLD1  =1, qFLDL2T=2,
	                                                   qFLDL2E=3, qFLDPI =4,
	                                                   qFLDLG2=5, qFLDLN2=6,
	                                                   qFLDZ  =7,
	   qFMONAD  = 11, // subc     fSD
	                                                   qFNEG=1, qFSQRT=2,
	                                                   qFABS=3,
	                                                   qFRND=4, qFREM=5,
	   qFDYAD   = 12, // subc     fSD
	                                                   qFCOM=1, qFADD=2,
	                                                   qFSUB=3, qFSUBR=4,
	                                                   qFMUL=5, qFDIV=6,
	                                                   qFDIVR=7,
	   qFPUSH   = 13, // fSD      fmf
	   qFPOP    = 14, // fSD      fmf
	   qPUSHR   = 15, // reg
	   qPOPR    = 16; // reg


}
