package iAPX.qPkt;

import iAPX.dataAddress.MemAddr;
import iAPX.enums.Kind;
import iAPX.enums.Opcode;

public class Qfrm2b extends Qfrm2 {
	MemAddr addr;
//	------------------------------------------------------------------------
//	-- Format 2.  Generated by Qf2(fnc,subc,reg,aux)
//	-- Format 2b. Generated by Qf2b(fnc,subc,reg,aux,addr)
//	------------------------------------------------------------------------
//	Visible Record Qfrm2b:Qfrm2;
//	begin infix(MemAddr) addr end;
//	------------------------------------------------------------------------
//	-- Mnemonic = FNC //   SUBC   REG    AUX   other   subcodes/comments
//	------------------------------------------------------------------------
	public final static int
//	%-E qLOADSC = 34, //   sreg   reg           addr
	   qPUSHC   = 35, //          reg   const
	                  //          reg   fld     addr
	   qLOADC   = 36; //          reg   const
	                  //          reg   fld     addr

	public Qfrm2b(Opcode fnc, int subc, int reg, int type, int aux, MemAddr addr) {
		super(fnc, subc, reg, type, aux);
		this.kind = Kind.K_Qfrm2b;
		this.addr = addr;
	}

}
