package iAPX.qPkt;

import static iAPX.util.Global.cANY;

import iAPX.enums.Kind;
import iAPX.enums.Opcode;

public class Qfrm6 extends Qpkt {
	int aux;
    public Qfrm5 jmp;
    int rela;    // Variant
    String smbx; // Variant
	
//	------------------------------------------------------------------------
//	-- Format 6.  Generated by Qf6(fnc,subc,reg,aux)
//	------------------------------------------------------------------------
//	Visible Record Qfrm6:Qpkt;
//	begin range(0:MaxWord) aux;
//	      ref(Qfrm5) jmp;
//	      variant infix(wWORD) rela;
//	      variant range(0:MaxWord) smbx;
//	end;
//	------------------------------------------------------------------------
//	-- Mnemonic = FNC //   SUBC   REG    AUX   other   subcodes/comments
//	------------------------------------------------------------------------
	public final static int
	   qFDEST   = 62, //                fixno       jmp
	   qBDEST   = 63, //                labno  rela jmp
	   qLABEL   = 64, //   subc         fixno  smbx
	                                                   qBPROC=1,qEPROC=2,

	   qMXX     = 64;

	public Qfrm6(Opcode fnc, int subc, int aux, String smbx) {
		this.kind = Kind.K_Qfrm6;
		this.fnc = fnc;
		this.subc = subc;
		this.aux = aux;
		this.type = cANY;
		this.smbx = smbx;

		this.reg = 0;
		this.jmp = null;
	}
}
